alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
databases:
  - cluster_name: chalo-blr1-a
    db_name: chalo_production
    db_user: pgdb
    engine: PG
    name: chalo-blr1-a
    production: true
    version: "14"
domains:
  - domain: www.chalo.digital
    type: PRIMARY
envs:
  - key: CHALO_APP_DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: postgresql://pgdb:AVNS_aQ65wQ05Xs2GiCL50hB@private-chalo-blr1-a-do-user-12742890-0.b.db.ondigitalocean.com:25060/chalo_production?sslmode=require
  - key: RAILS_MASTER_KEY
    scope: RUN_AND_BUILD_TIME
    value: ba3b97ff21dcf1d4536b380f280e0c6e
name: oyster-app
region: blr
services:
  - environment_slug: ruby-on-rails
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${chalo-blr1-a.DATABASE_URL}
    github:
      branch: main
      deploy_on_push: true
      repo: blueinsightdigital/chalo
    health_check:
      http_path: /cars
    http_port: 8080
    instance_count: 1
    instance_size_slug: professional-xs
    name: chalo
    routes:
      - path: /
    run_command: ./bin/rails assets:precompile && ./bin/rails server -p $PORT -e ${RAILS_ENV:-production}
    source_dir: /
